[project]
name = "polyglot"
version = "0.1.0"
description = ""
authors = [
    {name = "fcas",email = "f3l1nux@gmail.com"}
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "wheel (>=0.48.0,<0.49.0)",
    "pyicu (>=2.16.2,<3.0.0)",
    "pycld2 (>=0.42,<0.43)",
    "six (>=1.17.0,<2.0.0)",
    "morfessor (>=2.0.6,<3.0.0)",
    "numpy (>=2.5.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
